//------------------------------------------------------------------------------
// <auto-generated>
// 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaMarketProApp.Properties {
    using System;
    
    
 
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///    
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WaMarketProApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    
        /// </summary>
        internal static System.Drawing.Bitmap about_16 {
            get {
                object obj = ResourceManager.GetObject("about-16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   
        /// </summary>
        internal static System.Drawing.Bitmap about_64 {
            get {
                object obj = ResourceManager.GetObject("about-64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///    
        /// </summary>
        internal static System.Drawing.Bitmap bot_16 {
            get {
                object obj = ResourceManager.GetObject("bot-16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   
        /// </summary>
        internal static System.Drawing.Bitmap bot_64 {
            get {
                object obj = ResourceManager.GetObject("bot-64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///    
        /// </summary>
        internal static System.Drawing.Bitmap bot_message_16 {
            get {
                object obj = ResourceManager.GetObject("bot-message-16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///  
        /// </summary>
        internal static System.Drawing.Bitmap bot_message_64 {
            get {
                object obj = ResourceManager.GetObject("bot-message-64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///  
        /// </summary>
        internal static System.Drawing.Bitmap contactsend_16 {
            get {
                object obj = ResourceManager.GetObject("contactsend-16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///  
        /// </summary>
        internal static System.Drawing.Bitmap contactsend_64 {
            get {
                object obj = ResourceManager.GetObject("contactsend-64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///  
        /// </summary>
        internal static System.Drawing.Bitmap data_16 {
            get {
                object obj = ResourceManager.GetObject("data-16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///  
        /// </summary>
        internal static System.Drawing.Bitmap data_64 {
            get {
                object obj = ResourceManager.GetObject("data-64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///  
        /// </summary>
        internal static System.Drawing.Bitmap data_641 {
            get {
                object obj = ResourceManager.GetObject("data-641", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///  
        /// </summary>
        internal static System.Drawing.Bitmap data_642 {
            get {
                object obj = ResourceManager.GetObject("data-642", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///  
        /// </summary>
        internal static System.Drawing.Bitmap envato_16 {
            get {
                object obj = ResourceManager.GetObject("envato-16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///  
        /// </summary>
        internal static System.Drawing.Bitmap envato_64 {
            get {
                object obj = ResourceManager.GetObject("envato-64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///  
        /// </summary>
        internal static System.Drawing.Bitmap filter_16 {
            get {
                object obj = ResourceManager.GetObject("filter-16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///  
        /// </summary>
        internal static System.Drawing.Bitmap filter_64 {
            get {
                object obj = ResourceManager.GetObject("filter-64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///  
        /// </summary>
        internal static System.Drawing.Bitmap follow_16 {
            get {
                object obj = ResourceManager.GetObject("follow-16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///  
        /// </summary>
        internal static System.Drawing.Bitmap follow_64 {
            get {
                object obj = ResourceManager.GetObject("follow-64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///  
        /// </summary>
        internal static System.Drawing.Bitmap group_16 {
            get {
                object obj = ResourceManager.GetObject("group-16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///  
        /// </summary>
        internal static System.Drawing.Bitmap group_64 {
            get {
                object obj = ResourceManager.GetObject("group-64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///  
        /// </summary>
        internal static System.Drawing.Bitmap group2_64 {
            get {
                object obj = ResourceManager.GetObject("group2-64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///  
        /// </summary>
        internal static System.Drawing.Bitmap join_16 {
            get {
                object obj = ResourceManager.GetObject("join-16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///  
        /// </summary>
        internal static System.Drawing.Bitmap join_64 {
            get {
                object obj = ResourceManager.GetObject("join-64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///  
        /// </summary>
        internal static System.Drawing.Bitmap login_wa16 {
            get {
                object obj = ResourceManager.GetObject("login-wa16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///  
        /// </summary>
        internal static System.Drawing.Bitmap login_wa64 {
            get {
                object obj = ResourceManager.GetObject("login-wa64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///  
        /// </summary>
        internal static System.Drawing.Bitmap msg_16 {
            get {
                object obj = ResourceManager.GetObject("msg-16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///  
        /// </summary>
        internal static System.Drawing.Bitmap msg_64 {
            get {
                object obj = ResourceManager.GetObject("msg-64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///  
        /// </summary>
        internal static System.Drawing.Bitmap phone1_16 {
            get {
                object obj = ResourceManager.GetObject("phone1-16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///  
        /// </summary>
        internal static System.Drawing.Bitmap phone1_64 {
            get {
                object obj = ResourceManager.GetObject("phone1-64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE12F2EUFghXHA1ZvMkGzwdyC47gqYjB8igG978PUEMtAjlst6rUkrJf/7kzsirsPAYeYSRpmP/zlUtH1m1yPh2w== 的本地化字符串。
        /// </summary>
        internal static string pubKey {
            get {
                return ResourceManager.GetString("pubKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///  
        /// </summary>
        internal static System.Drawing.Bitmap send1_16 {
            get {
                object obj = ResourceManager.GetObject("send1-16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///  
        /// </summary>
        internal static System.Drawing.Bitmap send1_64 {
            get {
                object obj = ResourceManager.GetObject("send1-64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///  
        /// </summary>
        internal static System.Drawing.Bitmap send1_641 {
            get {
                object obj = ResourceManager.GetObject("send1-641", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///  
        /// </summary>
        internal static System.Drawing.Bitmap tg_16 {
            get {
                object obj = ResourceManager.GetObject("tg-16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///  
        /// </summary>
        internal static System.Drawing.Bitmap tg_64 {
            get {
                object obj = ResourceManager.GetObject("tg-64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///  
        /// </summary>
        internal static System.Drawing.Bitmap tg1_16 {
            get {
                object obj = ResourceManager.GetObject("tg1-16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///  
        /// </summary>
        internal static System.Drawing.Bitmap tg1_64 {
            get {
                object obj = ResourceManager.GetObject("tg1-64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///  
        /// </summary>
        internal static System.Drawing.Bitmap wa2_16 {
            get {
                object obj = ResourceManager.GetObject("wa2-16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///  
        /// </summary>
        internal static System.Drawing.Bitmap wa2_64 {
            get {
                object obj = ResourceManager.GetObject("wa2-64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///  
        /// </summary>
        internal static System.Drawing.Bitmap website_16 {
            get {
                object obj = ResourceManager.GetObject("website-16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///  
        /// </summary>
        internal static System.Drawing.Bitmap website_64 {
            get {
                object obj = ResourceManager.GetObject("website-64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
